export { default as Footer } from './footer'
export { default as Header } from './header'
export { default as Main } from './main'
export { default as NotFound } from './not-found'
export { RootLayout, viewport } from './root-layout'
